# Generated by Django 5.0 on 2025-04-23 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('floor', models.PositiveSmallIntegerField(default=1, verbose_name='Этаж')),
                ('width', models.PositiveIntegerField(default=1000, verbose_name='Ширина (px)')),
                ('height', models.PositiveIntegerField(default=800, verbose_name='Высота (px)')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='office_layouts/', verbose_name='Фоновое изображение')),
                ('svg_data', models.TextField(blank=True, verbose_name='SVG данные')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Схема офиса',
                'verbose_name_plural': 'Схемы офиса',
                'ordering': ['floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('wall', 'Стена'), ('door', 'Дверь'), ('window', 'Окно'), ('column', 'Колонна'), ('area', 'Зона'), ('other', 'Другое')], default='wall', max_length=20, verbose_name='Тип элемента')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('x', models.FloatField(verbose_name='Координата X')),
                ('y', models.FloatField(verbose_name='Координата Y')),
                ('width', models.FloatField(default=0, verbose_name='Ширина')),
                ('height', models.FloatField(default=0, verbose_name='Высота')),
                ('rotation', models.FloatField(default=0, verbose_name='Поворот (градусы)')),
                ('svg_path', models.TextField(blank=True, verbose_name='SVG путь')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Цвет')),
                ('z_index', models.IntegerField(default=0, verbose_name='Z-индекс')),
                ('properties', models.JSONField(blank=True, default=dict, verbose_name='Свойства')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='office_layout.officelayout', verbose_name='Схема офиса')),
            ],
            options={
                'verbose_name': 'Элемент офиса',
                'verbose_name_plural': 'Элементы офиса',
                'ordering': ['z_index', 'element_type'],
            },
        ),
    ]
