# Generated by Django 5.0 on 2025-04-23 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('no_show', 'Неявка')], default='active', max_length=20, verbose_name='Статус')),
                ('reservation_type', models.CharField(choices=[('single', 'Однократное'), ('recurring', 'Повторяющееся')], default='single', max_length=20, verbose_name='Тип бронирования')),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('daily', 'Ежедневно'), ('weekdays', 'Будние дни'), ('weekly', 'Еженедельно'), ('biweekly', 'Раз в две недели'), ('monthly', 'Ежемесячно')], max_length=20, null=True, verbose_name='Шаблон повторения')),
                ('recurrence_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания повторений')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='Время прибытия')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='desks.desk', verbose_name='Рабочее место')),
                ('parent_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_reservations', to='reservations.reservation', verbose_name='Родительское бронирование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-start_time'],
            },
        ),
    ]
