# Generated by Django 5.0 on 2025-04-23 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('floor', models.PositiveSmallIntegerField(default=1, verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зоны',
            },
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('desk_number', models.CharField(max_length=20, unique=True, verbose_name='Номер стола')),
                ('x_coordinate', models.FloatField(verbose_name='Координата X')),
                ('y_coordinate', models.FloatField(verbose_name='Координата Y')),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('occupied', 'Занято'), ('maintenance', 'На обслуживании'), ('reserved', 'Зарезервировано')], default='available', max_length=20, verbose_name='Статус')),
                ('desk_type', models.CharField(choices=[('regular', 'Обычное'), ('standing', 'Стоячее'), ('meeting', 'Для встреч'), ('manager', 'Менеджерское')], default='regular', max_length=20, verbose_name='Тип стола')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='Особенности')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desks', to='desks.area', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Рабочее место',
                'verbose_name_plural': 'Рабочие места',
            },
        ),
    ]
